# Generated by Django 5.1.6 on 2025-03-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_matching", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Elemento",
            new_name="Element",
        ),
        migrations.CreateModel(
            name="Combination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_peso", models.IntegerField()),
                ("total_calorias", models.IntegerField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("elementos", models.ManyToManyField(to="app_matching.element")),
            ],
        ),
    ]
